// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAepy6G8TJ9c09_VBdHGVR3WrCUk7EYE1o',
    appId: '1:376980827682:web:ce194815e13d48f386a47b',
    messagingSenderId: '376980827682',
    projectId: 'movie-app-e4298',
    authDomain: 'movie-app-e4298.firebaseapp.com',
    storageBucket: 'movie-app-e4298.firebasestorage.app',
    measurementId: 'G-PY4HFXRCDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh60gmaGdYFjMLtfB_GiEEpVs7Vpsc-iQ',
    appId: '1:376980827682:android:16208cf2bac770ca86a47b',
    messagingSenderId: '376980827682',
    projectId: 'movie-app-e4298',
    storageBucket: 'movie-app-e4298.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHypbKD6LXOIkF29G6dz5kbcp8-wjozrs',
    appId: '1:376980827682:ios:7a401607b441762286a47b',
    messagingSenderId: '376980827682',
    projectId: 'movie-app-e4298',
    storageBucket: 'movie-app-e4298.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHypbKD6LXOIkF29G6dz5kbcp8-wjozrs',
    appId: '1:376980827682:ios:7a401607b441762286a47b',
    messagingSenderId: '376980827682',
    projectId: 'movie-app-e4298',
    storageBucket: 'movie-app-e4298.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAepy6G8TJ9c09_VBdHGVR3WrCUk7EYE1o',
    appId: '1:376980827682:web:80b05e2b5033560086a47b',
    messagingSenderId: '376980827682',
    projectId: 'movie-app-e4298',
    authDomain: 'movie-app-e4298.firebaseapp.com',
    storageBucket: 'movie-app-e4298.firebasestorage.app',
    measurementId: 'G-NG9MQV6ER8',
  );
}
